language: python

sudo: required
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

python:
  - 3.8

install:
  - pip install --quiet coveralls
  - pip install --quiet nose
  - pip install --quiet coverage
  - python setup.py install

script: 
  - nosetests --with-coverage --cover-package=pyequib

after_success:
  - coveralls
