language: python

sudo: required
before_install:
  - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

python:
  - 3.8

install:
  - pip install --quiet coveralls
  - pip install --quiet nose
  - pip install --quiet coverage
  - pip install --quiet jupyter_client
  - pip install --quiet ipykernel
  - pip install --quiet IPython
  - python setup.py install

script: 
  - nosetests
